src/CMakeLists.txt
I proposed this a long time ago on frei0r mailing list but somehow never ensured it made it to master...
=> Fix libmath linking crashes

configure.ac, doc/Makefile.am, src/filter/spillsupress/spillsupress.c
a couple of fixes taken from the Debian package `frei0r`
=> Debian fixes

src/filter/rgbsplit0r/rgbsplit0r.c
horizontal : right/left
vertical : up/down
=> rgbsplit0r : add both positive and negative directions

src/filter/c0rners/c0rners.c
=> fabsf() -> fabs()

src/filter/facebl0r/facebl0r.cpp
facebl0r : fix build
open cv version check was giving wrong result.
see #32
=> facebl0r / opencv : fix build

src/filter/bgsubtract0r/bgsubtract0r.c
=> bgsubstract0r : fix memory allocation

src/filter/emboss/emboss.c
=> emboss: initialize some variables to 0

src/filter/rgbsplit0r/rgbsplit0r.c
=> rgbsplit0r: Fix bounds checking and initialization

src/filter/baltan/baltan.cpp
This noticeably improves performance.
=> baltan: use calloc instead of malloc+memset

src/filter/nervous/nervous.cpp
This noticeably improves performance.
=> nervous: use calloc instead of malloc+memset

src/filter/timeout/timeout.cpp
=> timeout: set default parameter values, fix blending, fix rectangle height

src/filter/bluescreen0r/bluescreen0r.cpp, src/filter/cartoon/cartoon.cpp, src/filter/delay0r/delay0r.cpp, src/filter/edgeglow/edgeglow.cpp, src/filter/nosync0r/nosync0r.cpp, src/filter/primaries/primaries.cpp, src/filter/scanline0r/scanline0r.cpp, src/filter/sopsat/sopsat.cpp, src/filter/timeout/timeout.cpp, src/filter/vignette/vignette.cpp, src/filter/water/water.cpp, src/mixer2/xfade0r/xfade0r.cpp
=> change double parameter type in c++ plugins to match tutorial.cpp

include/frei0r_cairo.h, src/filter/cairogradient/cairogradient.c
=> cairogradient: fix order of color channels, typo

src/filter/delay0r/delay0r.cpp
=> delay0r: fix memory leak

src/filter/facebl0r/facebl0r.cpp, src/filter/facedetect/facedetect.cpp
=> facedetect/facebl0r: clean up header includes

src/Makefile.am, src/filter/CMakeLists.txt, src/filter/aech0r/CMakeLists.txt, src/filter/aech0r/aech0r.cpp
* Lighter or Darker mode
* Transform the echo to RGB world
TODO : Fix sse2 version - __SSE2__WIP
RGB plane fade is not ported in sse2 (m_rgb and m_flag_b tests)
files  :
src/Makefile.am
src/filter/CMakeLists.txt
+         src/filter/aech0r/aech0r.cpp
+         src/filter/aech0r/CMakeLists.txt
=> Add FX aech0r . Aim to simulate an analog video echo.

.github/workflows/main.yml, .releaserc
new automated build and release using github actions
🚧 work in progress 🚧
=> feat: github workflow for ci build

.github/workflows/main.yml, src/mixer2/burn/burn.cpp, src/mixer2/dodge/dodge.cpp, src/mixer2/overlay/overlay.cpp, src/mixer2/screen/screen.cpp, test/Makefile, test/frei0r-info.c
Starting a new test suite, first task accomplished is extract all info from plugins and save it into a json file. This helped find out anomalies in strings like newlines inside descriptions.
🚧 work in progress 🚧
=> feat: test suite

.github/workflows/release.yml
builds shared libs on ubuntu latest (22.04 at this time) and redistributes in the same way as win and osx
=> feat: add linux build and release

src/filter/keyspillm0pup/keyspillm0pup.c
=> Fix memory leak in keyspillm0pup

src/filter/colortap/colortap.c
=> Fix memory leak in colortap

src/filter/denoise/hqdn3d.c
=> Fix memory leak in hqdn3d

src/filter/pixs0r/pixs0r.cc
=> Fix shifting of rows by 0 pixels in pixs0r filter

src/mixer2/dodge/dodge.cpp
`MAX255` is not appropriate in this situation. 
This should resolves #29.
=> dodge: fix clamping to 0 - 255

src/filter/curves/curves.c, src/filter/delaygrab/delaygrab.cpp, src/filter/nervous/nervous.cpp, src/filter/vertigo/vertigo.c
This is no big deal. It just makes the code shorter and easier to read.
=> Do not check for NULL before calling free()

src/filter/water/water.cpp
contributed by @qq2225936589 in #106
=> fix: water filter

src/filter/filmgrain/filmgrain.c, src/filter/gateweave/gateweave.c
This fixes this issue https://github.com/dyne/frei0r/issues/189
=> Gateweave, Filmgrain - change inline functions to static inline

include/frei0r.hpp
=> Fix cast to bool type in get_param_value()

src/filter/nosync0r/nosync0r.cpp
This new option shifts the image to the left.
The parameter names seem strange to me. The original parameter was called "hsync offset". However, if moves the image up and down. Wouldn't that be "vertical"?
In keeping the the pattern, I named this new parameter "vsync offset". However, it moves the image left and right. Wouldn't that be "horizontal"?
=> Add vsync option to nosync0r filter

.github/workflows/release.yml, .github/workflows/test.yml, CMakeLists.txt, cmake/modules/TargetDistclean.cmake
See https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and- removed-features
> Compatibility with versions of CMake older than 3.5 has been removed.
=> Fix configuring with CMake version 4
